epochs: 10
lr: 1.0e-3
seed: 42

model: detr
pretrained_weights: "facebook/detr-resnet-50"
# checkpoint_path_in:
checkpoint_path_out: "/hkfs/work/workspace/scratch/ih5525-E2/Hackasaurus-Rex/models/DETR/"

data:
  data_root: '/hkfs/work/workspace/scratch/ih5525-energy-train-data'
  batch_size: 12
  workers: 6
  pin_memory: False
  persistent_workers: True
  prefetch_factor: 4

split_data: True
comm_method: nccl-slurm
mode: detr
