epochs: 1
lr: 1.0e-3
seed: 42

model: yolo
model_checkpoint: 'yolov8n.pt'

data:
  data_root: '/hkfs/work/workspace/scratch/ih5525-energy-train-data'
  batch_size: 10
  workers: 6
  pin_memory: True
  persistent_workers: True
  prefetch_factor: 4
